apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: metaflow-
spec:
  entrypoint: metaflow-run
  serviceAccountName: argo
  templates:
  - name: metaflow-run
    container:
      image: 282052313230.dkr.ecr.ap-south-1.amazonaws.com/metaflow-argo:latest
      command: ["python"]
      args: ["flow.py", "run"]
      env:
        - name: USER
          value: github-runner

