name: Metaflow CI/CD with Argo

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  ECR_REPO: metaflow-argo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Build & Push Docker image
      run: |
        docker build -t $ECR_REPO .
        docker tag $ECR_REPO:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$ECR_REPO:latest
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$ECR_REPO:latest

    - name: Install Argo CLI
      run: |
        ARGO_VERSION=v3.4.8
        curl -sLO https://github.com/argoproj/argo-workflows/releases/download/${ARGO_VERSION}/argo-linux-amd64
        chmod +x argo-linux-amd64
        sudo mv argo-linux-amd64 /usr/local/bin/argo
        argo version 

    - name: Submit Argo Workflow
      run: |
        curl -sLO https://github.com/argoproj/argo-workflows/releases/latest/download/argo-linux-amd64
        chmod +x argo-linux-amd64 && mv argo-linux-amd64 /usr/local/bin/argo
        aws eks update-kubeconfig --region $AWS_REGION --name ${{ secrets.EKS_CLUSTER_NAME }}
        argo submit -n argo argo-metaflow.yaml --serviceaccount argo --watch

